### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by analytically** [signalfx/docker-zookeeper#5]
Due to https://github.com/signalfuse/maestro-ng/commit/8a11dd7a45ca8beb1a7f33cd427bb3c7d557a194

**Comment by mpetazzoni** [comment]
@analytically That's a pretty old commit. Can you elaborate at what's wrong with the image and what's not working for you?

Thanks!

**Comment by analytically** [comment]
`key = '{}_INSTANCES'.format(_to_env_var_name(service))`

This is never set in the Docker container...
